### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed. on windows 8.1 x64

### ISSUE THREAD

**Issue by snurkabill** [quantego/clp-java#9]
Hello, 

the library looks amazing, but I have problems to run it on windows 8.1 64bit. When running unit tests, multiple error msgs occur:
BridJ: LoadLibrary error when loading C:\Users\USER_NAME\AppData\Local\Temp\CLPExtractedLib454367849497120\Clp.dll : A dynamic link library (DLL) initialization routine failed. 

and then test fails: 

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 51.48 sec <<< FAILURE!
testToString(com.quantego.clp.CLPTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: com.quantego.clp.CLPNative.clpNewModel()Lorg/bridj/Pointer;
	at com.quantego.clp.CLPNative.clpNewModel(Native Method)
	at com.quantego.clp.CLP.init(CLP.java:75)
	at com.quantego.clp.CLP.<init>(CLP.java:71)
	at com.quantego.clp.CLPTest.testToString(CLPTest.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

unfortunately, I need this to be runnable on windows. Please, help me.

**Comment by loehndorf** [comment]
I only recompiled CLP two weeks ago, as I ran into similar issues under Windows 10. The develop branch already contains the update, so does the released Jar. I will merge and push this into the master branch soon. Then, I will also update the Maven Central Repository.
